# Домашнее задание к занятию
"Классификация: Логистическая регрессия и SVM"

## Логистическая регрессия

In [1]:
import numpy as np
import pandas as pd 
import scipy.stats 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
data = pd.read_csv('adult_csv.csv')
data

age         workclass  fnlwgt  education  education-num  \
0        2         State-gov   77516  Bachelors             13   
1        3  Self-emp-not-inc   83311  Bachelors             13   
2        2           Private  215646    HS-grad              9   
3        3           Private  234721       11th              7   
4        1           Private  338409  Bachelors             13   
...    ...               ...     ...        ...            ...   
48837    2           Private  215419  Bachelors             13   
48838    4               NaN  321403    HS-grad              9   
48839    2           Private  374983  Bachelors             13   
48840    2           Private   83891  Bachelors             13   
48841    1      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation    relationship  \
0           Never-married       Adm-clerical   Not-in-family   
1      Married-civ-spouse    Exec-managerial         Husband   
2                Divorced  Handlers-cleaners   Not-in-family   
3      Married-civ-spouse  Handlers-cleaners         Husband   
4      Married-civ-spouse     Prof-specialty            Wife   
...                   ...                ...             ...   
48837            Divorced     Prof-specialty   Not-in-family   
48838             Widowed                NaN  Other-relative   
48839  Married-civ-spouse     Prof-specialty         Husband   
48840            Divorced       Adm-clerical       Own-child   
48841  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex  capitalgain  capitalloss  hoursperweek  \
0                   White    Male            1            0             2   
1                   White    Male            0            0             0   
2                   White    Male            0            0             2   
3                   Black    Male            0            0             2   
4                   Black  Female            0            0             2   
...                   ...     ...          ...          ...           ...   
48837               White  Female            0            0             2   
48838               Black    Male            0            0             2   
48839               White    Male            0            0             3   
48840  Asian-Pac-Islander    Male            2            0             2   
48841               White    Male            0            0             3   

      native-country  class  
0      United-States  <=50K  
1      United-States  <=50K  
2      United-States  <=50K  
3      United-States  <=50K  
4               Cuba  <=50K  
...              ...    ...  
48837  United-States  <=50K  
48838  United-States  <=50K  
48839  United-States  <=50K  
48840  United-States  <=50K  
48841  United-States   >50K  

[48842 rows x 15 columns]

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             48842 non-null  int64 
 1   workclass       46043 non-null  object
 2   fnlwgt          48842 non-null  int64 
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64 
 5   marital-status  48842 non-null  object
 6   occupation      46033 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capitalgain     48842 non-null  int64 
 11  capitalloss     48842 non-null  int64 
 12  hoursperweek    48842 non-null  int64 
 13  native-country  47985 non-null  object
 14  class           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [3]:
data = data[pd.isnull(data['native-country']) == 0 ] # исключаем нулевые поз
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 47985 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   age             47985 non-null  int64 
 1   workclass       45232 non-null  object
 2   fnlwgt          47985 non-null  int64 
 3   education       47985 non-null  object
 4   education-num   47985 non-null  int64 
 5   marital-status  47985 non-null  object
 6   occupation      45222 non-null  object
 7   relationship    47985 non-null  object
 8   race            47985 non-null  object
 9   sex             47985 non-null  object
 10  capitalgain     47985 non-null  int64 
 11  capitalloss     47985 non-null  int64 
 12  hoursperweek    47985 non-null  int64 
 13  native-country  47985 non-null  object
 14  class           47985 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.9+ MB


In [4]:
selectedColumns = data [['education-num', 'occupation','sex']]
#выбираем колонки образование,род занятий, пол

In [5]:
X = pd.get_dummies (selectedColumns)
X

education-num  occupation_Adm-clerical  occupation_Armed-Forces  \
0                 13                        1                        0   
1                 13                        0                        0   
2                  9                        0                        0   
3                  7                        0                        0   
4                 13                        0                        0   
...              ...                      ...                      ...   
48837             13                        0                        0   
48838              9                        0                        0   
48839             13                        0                        0   
48840             13                        1                        0   
48841             13                        0                        0   

       occupation_Craft-repair  occupation_Exec-managerial  \
0                            0                           0   
1                            0                           1   
2                            0                           0   
3                            0                           0   
4                            0                           0   
...                        ...                         ...   
48837                        0                           0   
48838                        0                           0   
48839                        0                           0   
48840                        0                           0   
48841                        0                           1   

       occupation_Farming-fishing  occupation_Handlers-cleaners  \
0                               0                             0   
1                               0                             0   
2                               0                             1   
3                               0                             1   
4                               0                             0   
...                           ...                           ...   
48837                           0                             0   
48838                           0                             0   
48839                           0                             0   
48840                           0                             0   
48841                           0                             0   

       occupation_Machine-op-inspct  occupation_Other-service  \
0                                 0                         0   
1                                 0                         0   
2                                 0                         0   
3                                 0                         0   
4                                 0                         0   
...                             ...                       ...   
48837                             0                         0   
48838                             0                         0   
48839                             0                         0   
48840                             0                         0   
48841                             0                         0   

       occupation_Priv-house-serv  occupation_Prof-specialty  \
0                               0                          0   
1                               0                          0   
2                               0                          0   
3                               0                          0   
4                               0                          1   
...                           ...                        ...   
48837                           0                          1   
48838                           0                          0   
48839                           0                          1   
48840                           0                          0   
48841                           0                          0   

       occupation_

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit( data['class'])#переведем значения столбца class в числа, оставив один столбец
y = pd.Series (data = le.transform(data['class'])) 
y

0        0
1        0
2        0
3        0
4        0
        ..
47980    0
47981    0
47982    0
47983    0
47984    1
Length: 47985, dtype: int32

In [7]:
from sklearn.pipeline import make_pipeline 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [8]:
model = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))
# используем пайплайны для удобства, приводим в единую размерность 
# берем в качестве модели логистическую регресиию

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [10]:
model.fit(X_train, y_train)
predictions = model.predict(X_test)

In [11]:
predictions[:5]

array([0, 0, 0, 0, 1])

In [12]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
model.predict_proba(X_test)

array([[0.8144155 , 0.1855845 ],
       [0.96213234, 0.03786766],
       [0.69508013, 0.30491987],
       ...,
       [0.78157187, 0.21842813],
       [0.78157187, 0.21842813],
       [0.93274083, 0.06725917]])

In [14]:
model.score(X_train, y_train)

0.7967191640120277

In [15]:
model.score(X_test, y_test)

0.7933453737149209

## Метод опорных векторов. SVM.

In [16]:
from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(), SVC(gamma='auto')) 
clf.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('svc', SVC(gamma='auto'))])

In [17]:
clf.score(X_train, y_train) 

0.7970764238292298

In [18]:
clf.score(X_test, y_test)

0.7948041122534037